In [9]:
import numpy as np
x= np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56,58, 60]).reshape(5,2,3)
print(x)

[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]

 [[26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]]

 [[50 52 54]
  [56 58 60]]]


In [115]:
x= np.arange(1, 30, 2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [62]:
np.asarray(np.mat("1 2 3 4 5 6;7 8 9 10 11 12;13 14 15 16 17 18;19 20 21 22 23 24;25 26 27 28 29 30"))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [107]:
np.array([[1, 2, 3, 4, 5, 6, 7, 8],[1, 2 ,3 ,4 ,5 ,6, 7, 8],[1, 2, 3, 4, 5, 6, 7, 8],[1, 2, 3, 4, 5, 6, 7, 8]])

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])